### PR TITLE
Climate template update

### PR DESCRIPTION
**Pull request by iamzoltan**
this branch was created to test the process notebook workflow.

### CODE REVIEW

**Comment by iamzoltan** [comment]
@OhadZivan @jlpearso I created a new branch on the repo, and merged your forked branch into it. This way the workflow can run. It was trying to run, looking for a branch that doesnt exist. We will need to have contributors create branches on the main repo or do it this way.

**Comment by jlpearso** [comment]
> @OhadZivan @jlpearso I created a new branch on the repo, and merged your forked branch into it. This way the workflow can run. It was trying to run, looking for a branch that doesnt exist. We will need to have contributors create branches on the main repo or do it this way.

Sounds good! Whatever is easiest to keep our user numbers manageable is fine by me. :)

**Comment by jlpearso** [comment]
@iamzoltan looking over the code report, is it a problem that there are 65 violations in pycodestyle? How does this compare with the previous version of the template minus our edits?

comparing the instructor to student notebooks I don't see any major issues but note when I do hit the 'click for solution' links in the student version it takes me to a 404 for exercise solutions and explanations except for the very last one. Wanted to make sure this is expected behavior.

Can you comment on if the feedback gadget is working? It doesn't produce anything in these notebooks and clicking didn't seem to work in the book before either.

Same thing for the air table for the discussion section towards the bottom. The code remains the same and doesn't produce anything. How might we use this feature as it seems like it could be a valuable tool for TAs?

**Comment by OhadZivan** [comment]
> W1D2_Tutorial1
> Instructor	[Open In Colab](https://colab.research.google.com/github/neuromatch/course-content-template/blob/climate-template-update/tutorials/W1D2_Template/W1D2_Tutorial1.ipynb)
> Student	[Open In Colab](https://colab.research.google.com/github/neuromatch/course-content-template/blob/climate-template-update/tutorials/W1D2_Template/student/W1D2_Tutorial1.ipynb)
> Code report for W1D2_Tutorial1
> # Code report for W1D2_Tutorial1.ipynb
> ## Quality (pyflakes)
> Total code issues: 0
> 
> ## Style (pycodestyle)
> Total PEP8 violations: 65
> 
> Common problems:
> 
> * 16 instances of E402 (module level import not at top of file)
> * 12 instances of E265 (block comment should start with '# ')
> * 5 instances of E266 (too many leading '#' for block comment)
> * 5 instances of E302 (expected 2 blank lines, found 1)
> * 4 instances of E305 (expected 2 blank lines after class or function definition, found 1)
> * 2 instances of E302 (expected 2 blank lines, found 0)
> * 2 instances of E261 (at least two spaces before inline comment)
> * 2 instances of E501 (line too long (91 > 88 characters))
> * 2 instances of E501 (line too long (115 > 88 characters))
> * 2 instances of E703 (statement ends with a semicolon)

I've got more technical questions.
a few of these are missing blank lines. and others have to long lines. 
it was never part of the instructions. do we really need such limitations? number of characters in a line? why is it even an issue? 

only thing I agree with is the semicolon 😆

**Comment by iamzoltan** [comment]
PEP8 is a guideline for python styling. In general, code you find in most libs or FOSS projects will follow that styling. It is not necessary for the function of python or our books, but it is generally preferred in the python community and makes reading code much easier.

**Comment by OhadZivan** [comment]
as long as it's not mandatory

**Comment by jlpearso** [comment]
@iamzoltan can you comment on these things as well please when you have time?

> @iamzoltan looking over the code report, is it a problem that there are 65 violations in pycodestyle? How does this compare with the previous version of the template minus our edits? _ this was solved in Ohad convo above
> 
> comparing the instructor to student notebooks I don't see any major issues but note when I do hit the 'click for solution' links in the student version it takes me to a 404 for exercise solutions and explanations except for the very last one. Wanted to make sure this is expected behavior.
> 
> Can you comment on if the feedback gadget is working? It doesn't produce anything in these notebooks and clicking didn't seem to work in the book before either.
> 
> Same thing for the #airtable for the discussion section towards the bottom. The code remains the same and doesn't produce anything. How might we use this feature as it seems like it could be a valuable tool for TAs?

**Comment by iamzoltan** [comment]
@jlpearso I am not sure which solutions you are talking about. when I click for them I get directed to the correct place. can you share a specific link?

**Comment by jlpearso** [comment]
@iamzoltan weird they work for me now!

**Pull request merged**
